name: fatigue_detect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.68.0 

  persistent_bottom_nav_bar: ^5.0.2

  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  camera: ^0.10.5+4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/profile.jpg
